apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ok7fc3yl7-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:6c388163574ddd2525bd01b3e37f650f9f100cff@sha256:2991f246453f10fbb4752831eea819b3e66f5ae93c3127ce0ccc47dbcb941ee5
          name: container-image
